### ISSUE TITLE
Omi's built-in transcription often fails or experiences significant lag

### ISSUE THREAD

**Issue by faraza** [BasedHardware/omi#1056] opened 2024-10-13 22:24 UTC
**Describe the bug**
Frequently, when I open the Omi app and start speaking, nothing appears on the transcription side for In Progress. Sometimes, it will appear after 60+ seconds, other times it will not appear at all.
This doesn't happen 100% of the time, but it does happen several times per day. I am building a plugin that involves analyzing the transcript in to real time. 10-15 seconds lag is okay. But longer than that is a dealbreaker.

**To Reproduce**
1. Open the Omi App
2. Turn on the Omi Device
3. Go to the memories tab
4. Start speaking
5. Often times, nothing will happen. Or text will not appear for 60+ seconds.

**Expected behavior**
When I speak, transcription text will appear within 10-15 seconds consistently without any problems.

**Screenshots**
![IMG_BDFCE3CB6BD0-1](https://github.com/user-attachments/assets/de9ce63c-19ef-48fd-9e8d-931cac9dcd82)

**Desktop (please complete the following information):**
iPhone 11 iOS 17.5.1
Friend V1 Firmware 1.0.4

**Smartphone (please complete the following information):**

**Additional context**
For testing this app, Joan let my Omi device bypass the VAD in the Server.

**Comment by beastoin** [comment] 2024-10-13 22:31
hi man, what app version do you use ?

**Comment by faraza** [comment] 2024-10-13 22:37
Sorry! Forgot to put that. 1.0.42+153

**Comment by beastoin** [comment] 2024-10-13 22:53
_Discussion moving to Discord._

**Comment by josancamon19** [comment] 2024-10-15 23:49
This is a duplicate of #1025

**Closed by josancamon19** 2024-10-15 23:49 UTC
