### ISSUE TITLE
When clicking on a notification, I am not redirected to the chat and don't see the full text in chat

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/omi#1328] opened 2024-11-16 00:02 UTC
**Describe the bug**
When clicking on a notification, I am not redirected to the chat and don't see the full text in chat

**To Reproduce**
receive a notificiation from one of omi apps, click on it

**Current behavior**
"memory" page opens. If I manually click on "chat" - i don't see notification text there. Only after I kill the app and reopen. i can see it

**Expected behavior**
I am redirected to chat page and I can see the notification as a message there. 

**user ID (can we access the user info to validate the bug?):**
viUv7GtdoHXbK1UBCDlPuTDuPgJ2

**Smartphone + device (please complete the following information):**
 - Device: iphone 13
- 1.0.46+171 

**Additional context**

**Comment by beastoin** [comment] 2024-11-16 01:55
@chiemduong97 lead / @nquang29 

for short: 
- support deeplink to navigate to chat page when users click to the notification
- auto-reload chat page

notices:
- dont spam the api /messages

**Comment by chiemduong97** [comment] 2024-11-19 06:12
PRs [https://github.com/BasedHardware/omi/pull/1359](url) #1359

**Comment by beastoin** [comment] 2024-11-22 02:28
@chiemduong97 i could not find it works on the latest update (b177 - main branch). please leave a check. 

the recently updates might be the cause ? https://github.com/BasedHardware/omi/pull/1370/files#diff-01d6333e48723efeb9ffe0e5e2c73a697032395cb3416d0f44b429cbb8884b4aR120-R121

https://github.com/user-attachments/assets/ef2fa701-39c2-4005-8372-a114976668a8

**Comment by beastoin** [comment] 2024-11-22 08:37
https://github.com/BasedHardware/omi/blob/main/app/lib/services/notifications.dart#L170-L179

https://github.com/BasedHardware/omi/blob/main/app/lib/services/notifications.dart#L266-L285

2 code blocks are conflicted leading to override the SharedPreferencesUtil().pageToShowFromNotification value

then the feature does not work as expected

@chiemduong97 @mdmohsin7 could you guy pls collaborate to resolve this issue ?

**Update:**

- nvm, resolved by https://github.com/BasedHardware/omi/pull/1379

**Comment by mdmohsin7** [comment] 2024-11-22 11:31
Already fixed lol
Very fast @beastoin

**Comment by chiemduong97** [comment] 2024-11-22 11:49
MRs [https://github.com/BasedHardware/omi/pull/1429](url) #1429

**Closed** 2024-11-25 02:37 UTC
