### ISSUE TITLE
Finish setting up codemagic

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Omi#525] opened 2024-08-05 21:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by legut2** [comment] 2024-08-08 11:04
I'm interested in helping out with this but it's a duplicate of [this issue](https://github.com/BasedHardware/Friend/issues/298) in some sense. I even suggested it on [there](https://github.com/BasedHardware/Friend/issues/298#issuecomment-2230841205). The reason I suggested it is because codemagic is designed around flutter and when I looked at fast lane - it didn't feel like it was designed with consideration of flutter at all. Which is a really nuanced but important detail for developer experience in my opinion.

**Comment by josancamon19** [comment] 2024-08-09 06:44
Awesome, thank you.

Assigning to @legut2

**Comment by josancamon19** [comment] 2024-08-09 06:45
There's an intiial implementation, please DM me your email on discord to give you access to codemagic org.
We are also using shorebird right now, do you know if there is a way to do shorebird but if we modified native code, to do the full release? @legut2 ?

**Comment by legut2** [comment] 2024-08-09 11:51
> There's an intiial implementation, please DM me your email on discord to give you access to codemagic org.
> 
> We are also using shorebird right now, do you know if there is a way to do shorebird but if we modified native code, to do the full release? @legut2 ?

I'm not familiar with shorebird and I cannot say. ~~Can you point me to where that integration exists relating to this repo?~~ Looks like there is a config file [here](https://github.com/BasedHardware/Omi/blob/7e632187fb9d2f513f0b2d8b5b0e68dfb02b0a37/app/shorebird.yaml#L4).

DM'd you on discord and linked this issue.

**Comment by yashas-hm** [comment] 2024-08-21 16:47
Hi, 

Is this implemented?

**Comment by legut2** [comment] 2024-08-21 17:38
@yashas-hm I am uncertain. I haven't received access from @josancamon19. I am unable to make any kind of progress on this. It's very confusing why there is [an issue for fast lane](https://github.com/BasedHardware/Omi/issues/298), [an issue for codemagic](https://github.com/BasedHardware/Omi/issues/525#top), but they're using shorebird? Those feel like competing issues that needlessly overlap in functionality and accomplish similar goals.

**Comment by yashas-hm** [comment] 2024-08-21 18:53
@legut2 According to what I have read on #298 and this issue, they have already implemented Shorebird and wanted to setup automated deployments but there is some confusion between fastlane and codemagic.
Shorebird is used for on the fly changes like minor bug fixes or text changes etc. of sorts but shouldn't be used to introduce new features or a major change.
For major changes and new features automated deployment would be preferable (creating & publishing a new release) hence implementing both shorebird and automated deployment makes sense.
I would recommend using codemagic over fastlane as codemagic was built taking flutter into mind and fastlane is a general ci/cd tool. Also Codemagic has a huge community for flutter support.

@josancamon19 please correct me if i'm wrong understanding the issues.
Thank you

**Closed** 2024-08-26 13:11 UTC
